// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace exercicio.Models;

public class Aluno
{
    [Key]
    public int Id { get; set; }

    [Required(ErrorMessage = "O Campo Nome é necessário.")]
    [StringLength(255)]
    [Display(Name = "Nome")]

    public string Nome { get; set; }

    [Required(ErrorMessage = "O Campo Sobrenome é necessário.")]
    [StringLength(255)]
    [Display(Name = "Sobrenome")]

    public string Sobrenome { get; set; }

    [Required(ErrorMessage = "O Campo Idade é necessário.")]
    
    public int Idade { get; set; }

    [Required(ErrorMessage = "O Campo Curso é necessário.")]
    [StringLength(255)]
    
    public string Curso { get; set; }
}